[programs.localnet]
marketplace1 = "6UKJXxeUxGvB3fjBCVhiRmoFzDMAFPQjhbyKRWmFqrw6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/biboux/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
